# Generated by Fazil Amirli 11.09.2021, 12:27

from bs4 import BeautifulSoup
import requests
import pandas as pd

pd.set_option("display.max_rows", 100)
source = requests.get('https://www.billboard.com/charts/year-end/hot-100-songs').text
soup = BeautifulSoup(source, 'lxml')

songs = soup.findAll('div', class_='ye-chart-item__title')
artists = soup.findAll('div', class_='ye-chart-item__artist')
artists_list = [artist.text.strip() for artist in artists]
song_list = [song.text.strip() for song in songs]
df = pd.DataFrame({'songs': song_list, 'artists': artists_list})
df.to_csv(path_or_buf="billboard_top_100.csv")
